
runtime: python27
api_version: 1
threadsafe: yes

# Handlers define how to route requests to your application.
handlers:
- url: .*  # This regex directs all routes to main.app
  script: app.__init__.app

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: flask-snapsend:us-east1:snapsend-mysql
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: snapsend
# [END env_variables]

libraries:
- name: MySQLdb
  version: "latest"

# temporary workaround around gcloud issue
skip_files:
- ^venv/.*$
- front/
