// flow-typed signature: b9586e303132bc15a0f73d7ac552c91c
// flow-typed version: <<STUB>>/bs-material-ui_v^0.2.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs-material-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs-material-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bs-material-ui/lib/js/src/MaterialUI' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bs-material-ui/lib/js/src/MaterialUI.js' {
  declare module.exports: $Exports<'bs-material-ui/lib/js/src/MaterialUI'>;
}
